### ISSUE TITLE
sparkle unexpectedly requires "sparkle:shortVersionString" in delta update feed items

### ISSUE THREAD

**Issue by core-code** [sparkle-project/Sparkle#1207]
1.) download https://github.com/aonez/Keka/releases/download/v1.0.14/Keka-1.0.14.zip
2.) "check for updates"
3.) you'll see "Keka 1804 is now available - you have 1.0.14." this obviously confusing message (which compares a bundleversion with a shortversionstring) is presented because sparkle seems to ignore the sparkle:shortVersionString information present in the update feed here: http://www.kekaosx.com/update/keka.xml
4.) since the feed is valid i don't know why sparkle ignores the shortversionstring in this feed, but uses it just fine for most other feeds. same bug exists when replacing the sparkle framework in Keka with the newest version 'Sparkle-1.19.0rc2'

**Comment by kornelski** [comment]
Keka 1.0.14 has Sparkle 1.14.0. Note that when updating an app, the new version of Sparkle is not used, since it's not even downloaded yet.

We've fixed display of shortVersionString in Sparkle 1.18.

**Comment by core-code** [comment]
i understand that the framework thats embedded into the app is used. but

1.) as i said, i've replaced the (old) Sparkle framework right inside the Keka app bundle with the new Sparkle-1.19.0rc2' version and the problem persists
2.) also when using the CLI tool in the 'XPC-and-UI-separation' tool to from GIT HEAD of that branch the problem is also observable:

**Comment by core-code** [comment]
note that you'll have problems reproducing it now with 'Keka', as they have fixed it server-side by changing the feed: https://github.com/aonez/Keka/issues/162

**Comment by kornelski** [comment]
Ahh! It was caused by the delta updates. That makes sense. It looks like an easy mistake to make, so we should probably use `<enclosure>` as a fallback for the deltas.

**Comment by zorgiepoo** [comment]
This really behaves expectably and `shortVersionString` is not different than `version` here. We should not fall back to main enclosure item. We already fall back to `version` and `shortVersionString` being app cast attribute items, which is the correct approach, and I believe we have done this for a very long time. I think the correct adjustment documentation wise is to use the appcast item attributes for version fields in our sample app casts / generate_appcast.
